name: GA4 TDS

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 0 * * *"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 24f1001895@ds.study.iitm.ac.in
        run: echo "24f1001895@ds.study.iitm.ac.in"
